---
- name: QR code setup
  hosts: RB
  become: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        force_apt_get: yes
    - name: Install QR code generator
      apt: name=qrencode
    - name: Check installed version
      command: qrencode -V | head -n 1
      register: qrenver
    - debug: 
        msg: "Installed version is {{ qrenver.stdout }}"
    - name: Generate WLAN 2.4GHz QR code
      command: qrencode -s 5 -o /home/pi/git/wlan-QR/wifi24.png 'WIFI:S:ARRIS-EB72;T:WPA2;P:116C92139952DAD1;;'
    - name: Generate WLAN 5GHz QR code
      command: qrencode -s 5 -o /home/pi/git/wlan-QR/wifi5.png 'WIFI:S:ARRIS-EB72-5G;T:WPA2;P:116C92139952DAD1;;'
    
