---
- name: QR code setup
  hosts: RB
  become: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        force_apt_get: yes
    - name: Install QR code generator
      apt: name=qrencode
    - name: Check installed version
      command: qrencode -V | head -n 1
      register: qrenver
    - debug: 
        msg: "Installed version is {{ qrenver.stdout }}"
    - name: Generate WLAN 2.4GHz QR code
      command: qrencode -s 5 -o [insert directory]/wifi24.png 'WIFI:S:[insert ssid];T:WPA2;P:[insert password];;'
    - name: Generate WLAN 5GHz QR code
      command: qrencode -s 5 -o [insert directory]/wifi5.png 'WIFI:S:[insert ssid];T:WPA2;P:[insert password];;'
    
